# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pylgs',
                'doc_host': 'https://simonkeys.github.io',
                'git_url': 'https://github.com/simonkeys/pylgs',
                'lib_path': 'pylgs'},
  'syms': {'pylgs.all': {}, 'pylgs.imports': {}}}
