"""Extra functionality for [sparse](https://sparse.pydata.org) and [scipy.sparse](https://docs.scipy.org/doc/scipy/reference/sparse.html)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/utilities/sparse.ipynb.

# %% auto #0
__all__ = ['sparse2d_rand', 'spilu', 'sparse2d', 'sparse', 'sparse2d_identity', 'sparse_identity', 'sparse2d_diag', 'sparse_diag',
           'dense_toeplitz', 'sparse_toeplitz', 'sparse2d_kronecker_matrix', 'sparse_kronecker_matrix', 'kron',
           'restrict_bandwidth']

# %% ../../nbs/api/utilities/sparse.ipynb #867baa2c-2f84-440e-aff6-554889b83e45
import itertools as it

from fastcore.meta import delegates

import numpy as np
from numpy import array, ndarray
import scipy.sparse as sps
from scipy.sparse import sparray
import scipy.linalg as spl
import scipy.sparse.linalg as spa
from sparse import COO, GCXS, SparseArray
import sparse as ss

# %% ../../nbs/api/utilities/sparse.ipynb #1570e7c1-212e-4c06-bdc4-f427e417aebd
def sparse2d(a):
    """Create a 2D sparse array in specified format."""
    if isinstance(a, SparseArray): a = a.to_scipy_sparse()
    return sps.csr_array(a)

# %% ../../nbs/api/utilities/sparse.ipynb #216f4a2d-c16c-4d4e-80bf-691c7b27738b
@delegates(COO, but='data')
def sparse(a, format='coo', shape=None, **kwargs)->SparseArray:
    """Create an N-D sparse array in specified format."""
    if format == 'gcxs': cls = GCXS
    elif format == 'coo': cls = COO
    if isinstance(a, ndarray): return cls.from_numpy(a)
    if sps.issparse(a): return cls.from_scipy_sparse(a)
    if isinstance(a, SparseArray): return cls(a)
    # Assume a is coords and data in COO format
    if shape is None: shape = [max(c) - min(c) + 1 for c in a[0]]
    return cls(COO(*a, shape=shape, **kwargs))

# %% ../../nbs/api/utilities/sparse.ipynb #7086e75b-0760-46aa-886e-6758814c0c1d
def sparse2d_identity(n):
    return sps.eye_array(n)

# %% ../../nbs/api/utilities/sparse.ipynb #8d87c46c-4ac4-486b-80d6-21ed93c0b7e5
def sparse_identity(n, format='coo')->SparseArray:
    return ss.eye(n, format=format)

# %% ../../nbs/api/utilities/sparse.ipynb #16ae675f-b27c-4803-991d-28112d0087f2
def sparse2d_diag(diags, offsets=0):
    return sps.diags_array(diags, offsets=offsets)

# %% ../../nbs/api/utilities/sparse.ipynb #2a5e0268-db2b-487f-b6c0-e91bc6774790
def sparse_diag(diag, format='coo')->SparseArray:
    return sparse(sparse2d_diag(diag), format=format)

# %% ../../nbs/api/utilities/sparse.ipynb #a78fc1e9-1768-474a-864e-4a96b4fa2c08
def dense_toeplitz(
    diags:ndarray, # Value on each diagonal, starting at lower left.
):
    """Return a toeplitz array given the value on each diagonal (starting at lower left)."""
    n = (len(diags) - 1) // 2
    return spl.toeplitz(diags[:n+1][::-1], diags[n:])

# %% ../../nbs/api/utilities/sparse.ipynb #7deac9c3-f8fc-4542-ad6e-6f620a61be64
def sparse_toeplitz(
    diags:ndarray, # Value on each diagonal, starting at lower left.
    format='coo'
)->SparseArray:
    """Return a toeplitz sparse array in specified format given the value on each diagonal (starting at lower left)."""
    return sparse(dense_toeplitz(diags), format=format)

# %% ../../nbs/api/utilities/sparse.ipynb #e7d86fe4-b01a-44ae-9d42-88a37dd23302
def sparse2d_kronecker_matrix(n, k=0):
    """The nxn sparse kronecker matrix delta_(i,j-k) in specified format."""
    return sparse2d_diag(np.ones(n - abs(k)), offsets=k)

# %% ../../nbs/api/utilities/sparse.ipynb #ec8ec8e1-e00a-4730-831b-48491ad41cb4
def sparse_kronecker_matrix(n, k=0, format='coo')->SparseArray:
    """The nxn sparse kronecker matrix delta_(i,j-k) in specified format."""
    return sparse(sparse2d_kronecker_matrix(n, k), format=format)

# %% ../../nbs/api/utilities/sparse.ipynb #e9b96a8e-59f0-4bbe-b3a3-d98db4f1bc92
def kron(a, b, *rest):
    if rest: return kron(kron(a, b), *rest)
    if sps.issparse(a) or sps.issparse(b): 
        return sps.kron(a, b, format='csr')
    return np.kron(a, b)

# %% ../../nbs/api/utilities/sparse.ipynb #f2eecd9f-1433-4716-96e7-0d4edad7a5c0
sparse2d_rand = sps.random_array

# %% ../../nbs/api/utilities/sparse.ipynb #7638fadc-7bab-4ccc-9fa8-f1a431a1dc6f
spilu = spa.spilu

# %% ../../nbs/api/utilities/sparse.ipynb #36e9391f-3316-4588-acf6-1c1448d5ee96
def restrict_bandwidth(a_sparray:sparray, width):
    """Make a scipy sparse array banded by setting all elements outside the bandwidth to zero."""
    result = a_sparray.copy()
    i, j = result.nonzero()
    result.data[np.abs(i - j) > width] = 0.
    result.eliminate_zeros()
    return result
