"""Extra functionality for [xarray](https://xarray.pydata.org/)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/utilities/xarray.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/api/utilities/xarray.ipynb #675def04-42c4-4275-8cec-2216deb605f0
from fastcore.basics import patch
from xarray import Coordinates
import numpy as np

# %% ../../nbs/api/utilities/xarray.ipynb #7a626789-58c0-43e4-8886-c1ed3b702b34
@patch
def __add__(self:Coordinates, other):
    """Adding two `Coordinates` objects combines their coordinates."""
    if not isinstance(other, Coordinates): raise TypeError
    result = self.copy()
    result.update(other)
    return result

# %% ../../nbs/api/utilities/xarray.ipynb #78997e7b-bdf1-4938-824c-24e469144216
@patch
def complement(self:Coordinates, other:Coordinates):
    """Return coordinates not in other coordinates."""
    return Coordinates({k: v for k, v in self.items() if k not in other})

# %% ../../nbs/api/utilities/xarray.ipynb #06d0f3c0-00c0-4227-8458-dffbb9ca5c42
@patch(as_prop=True)
def shape(self:Coordinates):
    """Return tuple of sizes of the coordinates."""
    return tuple(self.sizes.values())

# %% ../../nbs/api/utilities/xarray.ipynb #f66cc1f3-d860-4709-b628-2121f9130d43
@patch(as_prop=True)
def size(self:Coordinates):
    """Return product of coordinate lengths."""
    return np.prod(self.shape)

# %% ../../nbs/api/utilities/xarray.ipynb #da572816-99b8-4dca-b6cd-b790054be195
@patch
def intersection(self:Coordinates, other:Coordinates):
    """Return coordinates in self and other."""
    return Coordinates({k: v for k, v in self.items() if k in other and v.equals(other[k])})

# %% ../../nbs/api/utilities/xarray.ipynb #555da6b4-cbfe-44d2-bd9a-277495eb043c
@patch
def contain(self:Coordinates, other:Coordinates):
    """Return true if all coordinates in `other` are in `self`, otherwise false."""
    return self.intersection(other).equals(other)
