name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Install SUNDIALS
        run: sudo apt-get -y install libsundials-dev
      - uses: fastai/workflows/quarto-ghp@master
