name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Install SUNDIALS
        run: sudo apt-get -y install libsundials-dev
      - uses: fastai/workflows/nbdev-ci@master
